[package]
name = "zellij-layout-generator"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
shell-quote = "0.7.1"
toml = "0.8.19"

[dev-dependencies]
tempfile = "3.14.0"
