[package]
name = "zellij-layout-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"

[dev-dependencies]
tempfile = "3.14.0"
